### ISSUE TITLE
Unable to run `secureboot` target.

### ISSUE THREAD

**Issue by lucasaf04** [CAmadeus/falcon-tools#3]
```
Mailbox 0: 84018E00
Mailbox 1: 6C4EE1E4
TSEC Key: 00000000000000000000000000000000
ERROR FFFFFFFF
Last traced Program Counter: 00000094
Faulting Program Counter: 00000200
Esception Clause: Authentication Entry
```

I'm able to run requiem getting `Mailbox 1: BADC0DED`. For this target I'm using the same `KEY` and `SEED`.

(I've updated `faucon_laucher` to BDK 5.6 to support my OLED console)

Thanks.

**Comment by StarrFox** [comment]
@vbe0201 can you take a look at this?

**Comment by lucasaf04** [comment]
I got it, there was an issue in my `faucon_launcher` update.
